// src/redux/slices/eventsSlice.js
import { createSlice } from '@reduxjs/toolkit';

const eventsSlice = createSlice({
  name: 'events',
  initialState: [
    {
      id: 1,
      title: 'Tech Summit 2025',
      date: '2025-08-20',
      location: 'Pune',
      seats: 20,
      image: '/images/tech.jpg',
      type: 'Workshop',
      category: 'Technology',
      details: 'An engaging summit exploring the latest in technology and innovation.',
      price: 100,
    },
    {
      id: 2,
      title: 'Music Fest',
      date: '2025-09-15',
      location: 'Mumbai',
      seats: 25,
      image: '/images/music.jpg',
      type: 'Concert',
      category: 'Entertainment',
      details: 'A vibrant music festival featuring renowned artists and bands.',
      price: 150,
    },
    {
      id: 3,
      title: 'Startup Meetup',
      date: '2025-09-22',
      location: 'Bangalore',
      seats: 15,
      image: '/images/startup.jpeg',
      type: 'Networking',
      category: 'Business',
      details: 'A meetup for entrepreneurs to network and share ideas.',
      price: 200,
    },
    {
      id: 4,
      title: 'Art Expo',
      date: '2025-10-01',
      location: 'Delhi',
      seats: 30,
      image: '/images/art-expo.jpeg',
      type: 'Exhibition',
      category: 'Art',
      details: 'An exhibition showcasing stunning artworks from various artists.',
      price: 250,
    },
    {
      id: 5,
      title: 'Food Carnival',
      date: '2025-10-10',
      location: 'Ahmedabad',
      seats: 40,
      image: '/images/food.jpeg',
      type: 'Festival',
      category: 'Food',
      details: 'A carnival celebrating diverse cuisines and culinary delights.',
      price: 300,
    },
    {
      id: 6,
      title: 'Wildlife Photography Camp',
      date: '2025-10-15',
      location: 'Ranthambore',
      seats: 12,
      image: '/images/wild.jpg',
      type: 'Workshop',
      category: 'Photography',
      details: 'A camp for photography enthusiasts to capture wildlife moments.',
      price: 350,
    },
    {
      id: 7,
      title: 'AI in Healthcare',
      date: '2025-10-22',
      location: 'Chennai',
      seats: 18,
      image: '/images/health.jpg',
      type: 'Conference',
      category: 'Technology',
      details: 'A conference discussing the impact of AI in the healthcare sector.',
      price: 400,
    },
    {
      id: 8,
      title: 'Clean Energy Fair',
      date: '2025-11-01',
      location: 'Hyderabad',
      seats: 20,
      image: '/images/energy.png',
      type: 'Exhibition',
      category: 'Environment',
      details: 'A fair promoting clean energy solutions and technologies.',
      price: 450,
    },
    {
      id: 9,
      title: 'Beachside Yoga Retreat',
      date: '2025-11-10',
      location: 'Goa',
      seats: 10,
      image: '/images/yoga.jpg',
      type: 'Retreat',
      category: 'Wellness',
      details: 'A rejuvenating yoga retreat by the beach.',
      price: 500,
    },
    {
      id: 10,
      title: 'Film & Culture Night',
      date: '2025-11-18',
      location: 'Kolkata',
      seats: 25,
      image: '/images/film.jpeg',
      type: 'Movie Screening',
      category: 'Entertainment',
      details: 'An evening celebrating films and cultural performances.',
      price: 550,
    },
    {
      id: 11,
      title: 'Space Tech Conference',
      date: '2025-11-24',
      location: 'Sriharikota',
      seats: 30,
      image: '/images/space.jpeg',
      type: 'Conference',
      category: 'Technology',
      details: 'A conference exploring advancements in space technology.',
      price: 600,
    },
    {
      id: 12,
      title: 'Cricket Analytics Hackathon',
      date: '2025-12-05',
      location: 'Nagpur',
      seats: 15,
      image: '/images/cric.jpeg',
      type: 'Hackathon',
      category: 'Sports',
      details: 'A hackathon focused on analytics in cricket.',
      price: 650,
    },
    {
      id: 13,
      title: 'Movie Night',
      date: '2025-11-05',
      location: 'Chennai',
      seats: 50,
      image: '/images/mnight.jpeg',
      type: 'Entertainment',
      category: 'Movies',
      details: 'Enjoy a relaxing evening with popular movies and snacks.',
      price: 700,
    },
    {
      id: 14,
      title: 'Sports Meet',
      date: '2025-12-01',
      location: 'Kolkata',
      seats: 60,
      image: '/images/sports.jpeg',
      type: 'Sports',
      category: 'Sports',
      details: 'A thrilling sports event featuring various competitions and activities.',
      price: 750,
    },
    {
      id: 15,
      title: 'AI Conference',
      date: '2025-11-05',
      location: 'Hyderabad',
      seats: 50,
      image: '/images/ai.jpeg',
      type: 'Conference',
      category: 'Technology',
      details: 'A conference discussing the latest advancements in AI technology.',
      price: 800,
    },
    {
      id: 16,
      title: 'Film Festival',
      date: '2025-11-20',
      location: 'Chennai',
      seats: 60,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST1oRjMWP2y1wb1pZS_SdcHHGN5bsSeD3KBA&s',
      type: 'Festival',
      category: 'Entertainment',
      details: 'A celebration of cinema with screenings and discussions.',
      price: 850,
    },
    {
      id: 17,
      title: 'Coding Bootcamp',
      date: '2025-12-01',
      location: 'Kolkata',
      seats: 35,
      image: 'https://media.geeksforgeeks.org/wp-content/uploads/20230927184335/Best-Free-Coding-Bootcamps.png',
      type: 'Workshop',
      category: 'Education',
      details: 'An intensive bootcamp to enhance coding skills.',
      price: 900,
    },
    {
      id: 18,
      title: 'Literature Fest',
      date: '2025-12-15',
      location: 'Jaipur',
      seats: 45,
      image: 'https://www.publishingscotland.org/wp-content/uploads/2021/12/jaipur-literature-festival-website.jpg',
      type: 'Festival',
      category: 'Literature',
      details: 'A gathering of authors, poets, and literature enthusiasts.',
      price: 950,
    },
    {
      id: 19,
      title: 'Drone Racing League',
      date: '2025-12-20',
      location: 'Bangalore',
      seats: 30,
      image: '/images/drone.jpeg',
      type: 'Sports',
      category: 'Sports',
      details: 'An adrenaline-filled day with high-speed drone races and demonstrations.',
      price: 499,
    },
    {
      id: 20,
      title: 'Winter Coding Challenge',
      date: '2025-12-28',
      location: 'Delhi',
      seats: 40,
      image: '/images/winter.jpeg',
      type: 'Hackathon',
      category: 'Education',
      details: 'A winter-themed coding competition for developers of all levels.',
      price: 599,
    },
    {
      id: 21,
      title: 'Pathaan Premiere',
      date: '2025-12-30',
      location: 'Mumbai',
      seats: 100,
      image: '/images/pathan.jpeg',
      type: 'Movie Screening',
      category: 'Entertainment',
      details: 'Exclusive premiere of the latest Bollywood action thriller.',
      price: 350,
    },
    {
      id: 22,
      title: 'Rocky Aur Rani Ki Prem Kahani',
      date: '2025-12-31',
      location: 'Delhi',
      seats: 80,
      image: '/images/r.jpeg',
      type: 'Movie Screening',
      category: 'Entertainment',
      details: 'A romantic drama celebrating love and family.',
      price: 300,
    },
    {
      id: 23,
      title: 'Jawan Special Screening',
      date: '2026-01-05',
      location: 'Chennai',
      seats: 90,
      image: '/images/j.jpeg',
      type: 'Movie Screening',
      category: 'Entertainment',
      details: 'Special screening of the latest action-packed film.',
      price: 400,
    },
    {
      id: 24,
      title: 'Tiger 3 Release',
      date: '2026-01-10',
      location: 'Bangalore',
      seats: 110,
      image: '/images/tiger.jpeg',
      type: 'Movie Screening',
      category: 'Entertainment',
      details: 'Premiere of the blockbuster spy thriller.',
      price: 450,
    },
    {
      id: 25,
      title: 'Bhool Bhulaiyaa 3 Launch',
      date: '2026-01-15',
      location: 'Hyderabad',
      seats: 85,
      image: '/images/bb.jpeg',
      type: 'Movie Screening',
      category: 'Entertainment',
      details: 'Launch event for the much-anticipated horror-comedy sequel.',
      price: 320,
    },
  ],
  reducers: {
    addEvent(state, action) {
      state.push(action.payload);
    },
    deleteEvent(state, action) {
      return state.filter((e) => e.id !== action.payload);
    },
    decrementSeat(state, action) {
      const event = state.find((e) => e.id === action.payload);
      if (event && event.seats > 0) {
        event.seats -= 1;
      }
    },
  },
});

export const { addEvent, deleteEvent, decrementSeat } = eventsSlice.actions;
export default eventsSlice.reducer;
